### ISSUE TITLE
Failed to generate diagram - Error: Unable to calculate a unique id for an empty set of components

### ISSUE THREAD

**Issue by RobertoTorino** [pistazie/cdk-dia#30]
**npx cdk-dia fails with the following error:**

**% npx cdk-dia**
```
Failed to generate diagram - Error: Unable to calculate a unique id for an empty set of components
/usr/local/lib/node_modules/cdk-dia/node_modules/@aws-cdk/core/lib/private/uniqueid.js:33
        throw new Error('Unable to calculate a unique id for an empty set of components');
              ^
```
 
```
Error: Unable to calculate a unique id for an empty set of components
    at makeUniqueId (/usr/local/lib/node_modules/cdk-dia/node_modules/@aws-cdk/core/lib/private/uniqueid.js:33:15)
    at AwsEdgeResolver.findUniqueResourceId (/usr/local/lib/node_modules/cdk-dia/dist/src/diagram/aws/aws-edge-resolver.js:83:44)
    at /usr/local/lib/node_modules/cdk-dia/dist/src/diagram/aws/aws-edge-resolver.js:55:47
    at DiagramComponent.subTreeFindComponentRec (/usr/local/lib/node_modules/cdk-dia/dist/src/diagram/component/component.js:137:13)
    at DiagramComponent.subTreeFindComponent (/usr/local/lib/node_modules/cdk-dia/dist/src/diagram/component/component.js:134:21)
    at /usr/local/lib/node_modules/cdk-dia/dist/src/diagram/component/component.js:140:23
    at Array.map (<anonymous>)
    at DiagramComponent.subTreeFindComponentRec (/usr/local/lib/node_modules/cdk-dia/dist/src/diagram/component/component.js:139:40)
    at DiagramComponent.subTreeFindComponent (/usr/local/lib/node_modules/cdk-dia/dist/src/diagram/component/component.js:134:21)
    at AwsEdgeResolver.findTargetComponent (/usr/local/lib/node_modules/cdk-dia/dist/src/diagram/aws/aws-edge-resolver.js:54:47)
```
 
workaround for now: go to:
`/usr/local/lib/node_modules/cdk-dia/node_modules/@aws-cdk/core/lib/private`
 
**change this:**

```
function makeUniqueId(components) {
    components = components.filter(x => x !== HIDDEN_ID);
    if (components.length === 0) {
        throw new Error('Unable to calculate a unique id for an empty set of components');
    }
```
 
**to this:**
 
```
function makeUniqueId(components) {
    components = components.filter(x => x !== HIDDEN_ID);
    if (components.length < 0) {
        throw new Error('Unable to calculate a unique id for an empty set of components');
    }
```

**Comment by pistazie** [comment]
Before `cdk-dia` calls `makeUniqueId` it checks, that the components array isn't empty (`if (pathParts.length === 0) return false`).

Therefore, I guess [this line](https://github.com/aws/aws-cdk/blob/6b7ad6b605057972297e8879f0ff767545d1ce9a/packages/%40aws-cdk/core/lib/private/uniqueid.ts#L33  ) filters the component, creating an empty array.

Could you share some CDK code to help reproduce the issue? 

I would prefer trying to solve the issue downstream, then copying the non-exported `const HIDDEN_ID = 'Default';` variable to CDK-Dia.
